<?php

namespace App\Http\Controllers\Api\Driver;

use App\Http\Controllers\Controller;
use Illuminate\Http\Request;
use App\Models\User;
use App\Models\UserToken;
use App\Models\DriverLocation;
use Validator;
use Mail;
use App\Mail\WelcomeuserMail;
use Illuminate\Support\Facades\Hash;
use Spatie\Permission\Models\Role;

/**
 * @group Driver Authentication
 *
 * API endpoints for managing drivers authentication
 */

class AuthController extends Controller
{
    /**
     * Register Endpoint
     *
     * This endpoint allows you to register driver and generate token for authentication.
     * Along token driver details will be displayed. To call authorized endpoints you need access_token generated by this endpoint.
     *
     * @bodyParam   name string required The name of the driver. Example: Lucy Mark
     * @bodyParam   email email required The valid email of the driver. Example: lucy@example.com
     * @bodyParam   password string required The password of the driver. Example: secret
     *
     * @response {
     *      "status": true,
     *      "data": {
     *          "name": "Lucy",
     *          "email": "lucy@gmail.com",
     *          "id": 2
     *      },
     *      "access_token": "14|wiazS1DtHNXIWDToygChQD84uqU9HwVaU10nWVia",
     *      "token_type": "Bearer"
     *  }
     *
     */
    function register(Request $request)
    {
        $messages = array(
            'name.required' => __('Name field is required.'),
            'name.string' => __('Name must be string.'),
            'email.required' => __('Email field is required.'),
            'email.string' => __('Email must be string.'),
            'email.email' => __('Email address must be valid.'),
            'email.unique' => __('Email address is already taken.'),
            'password.required' => __('Password field is required.'),
            'password.string' => __('Password must be string.'),
            'password.min' => __('Password must be at-least 8 characters.')
        );
        $validator = Validator::make($request->all(), [
            'name' => 'required|string|max:255',
            'email' => 'required|string|email|unique:users',
            'password' => 'required|string|min:8'
        ], $messages);

        if ($validator->fails()) {
            return response()->json(['status' => false, 'errors' => $validator->errors()]);
        }

        $user = User::create([
            'name' => $request->name,
            'email' => $request->email,
            'password' => Hash::make($request->password),
            'status' => 0
        ]);
        $user->assignRole('Driver');
        $user->save();
        $token = $user->createToken('auth_token')->plainTextToken;
        unset($user->roles);
        unset($user->status);
        unset($user->created_at);
        unset($user->updated_at);
        //Mail::to($request->email)->send(new WelcomeuserMail($user));
        return response()
            ->json(['status' => true, 'data' => $user, 'access_token' => $token, 'token_type' => 'Bearer'], 201);
    }

    /**
     * Login Endpoint
     *
     * This endpoint allows you to generate token of driver after authentication.
     * Along token driver details will be displayed. To call authorized endpoints you need access_token generated by this endpoint.
     *
     * @bodyParam   email email required The valid email of the driver. Example: driver@example.com
     * @bodyParam   password string required The password of the driver. Example: secret
     *
     * @response {
     *      "status": true,
     *      "message": "You have successfully logged in!",
     *      "access_token": "13|JQHbQK8QuNHCzwztR30u2ogiBxuZNSBwJhZX8sop",
     *      "token_type": "Bearer",
     *      "data": {
     *          "id": 1,
     *          "name": "John Panda",
     *          "email": "panda@gmail.com",
     *          "status": 1
     *      }
     *  }
     *
     * @response 401 {
     *       "status": false,
     *       "message": "These credentials do not match our records!"
     *   }
     *
     * @response 403 {
     *       "status": false,
     *       "message": "Your account is not verified. Contact support!"
     *   }
     */

    function login(Request $request)
    {
        $messages = array(
            'email.required' => __('Email field is required.'),
            'email.email' => __('Email address must be valid.'),
            'password.required' => __('Password field is required.')
        );
        $validator = Validator::make($request->all(), [
            'email' => 'required|email',
            'password' => 'required'
        ], $messages);

        if ($validator->fails()) {
            return response()->json(['status' => false, 'errors' => $validator->errors()]);
        }
        $user = User::select(['id', 'name', 'email', 'password', 'status'])
            ->where('email', $request->email)
            ->first();
        if (!$user || !Hash::check($request->password, $user->password)) {
            return response([
                'status' => false,
                'message' => 'These credentials do not match our records!'
            ], 401);
        }elseif($user->status == 0){
            return response([
                'status' => false,
                'message' => 'Your account is not verified. Contact support!'
            ], 401);
        }
        $token = $user->createToken('auth_token')->plainTextToken;

        return response()
            ->json(['status' => true, 'message' => 'You have successfully logged in!', 'access_token' => $token, 'token_type' => 'Bearer', 'data' => $user], 200);
    }


      /**
     * Profile update Endpoint
     *
     * This endpoint allows you to update profile of user.
     * To update profile data you need access_token generated by this authentication endpoints.
     *
     * @bodyParam   name string optional Full name of the driver. Example: John Panda
     * @bodyParam   phone string optional Valid phone number the driver (International format). Example: +91234567890
     * @bodyParam   address string optional Valid full address of the driver. Example: Street 1, Main Block, XYZ
     * @bodyParam   image image optional Image should be less than 2MB and contains mentioned extensions (jpeg,png,jpg)
     * @bodyParam   city string optional City name of the driver
     * @bodyParam   country string optional Country name of the driver
     * @bodyParam   gender string optional Gender of the driver
     *
     * @response {
     *      "status": true,
     *      "message": "Your profile has been updated!",
     *  }
     *
     * @response 401 {
     *       "message": "Unauthenticated."
     *   }
     */


    function profileUpdate(Request $request){


        $messages = array(
            'image.image' => __('Image field must be image file type.'),
            'image.mimes' => __('Supported extensions for image are jpeg,png,jpg only.'),
            'image.max' => __('Image size should be less than 2MB.')
        );
        $validator = Validator::make($request->all(), [
            'image' => 'nullable|image|mimes:jpeg,png,jpg|max:2048',
        ], $messages);

        if ($validator->fails()) {
            return response()->json(['status' => false, 'errors' => $validator->errors()]);
        }

        //User from token
        $token = $request->user();

        $user = User::find($token->id);
        $user->name = $request->name;
        $user->phone = $request->phone;
        $user->gender = $request->gender;
        $user->city = $request->city;
        $user->country = $request->country;
        $user->address = $request->address;
        if($request->hasFile('image')){

            $imageName = time().'.'.$request->image->extension();
            $request->image->move(public_path('uploads/images/user/'), $imageName);
            $user->image = $imageName;
        }
        $user->save();

        return response()->json(['status' => true, 'message' => 'Your profile has been updated!', 'user'=> $user]);

    }


    /**
     * Device Token Store Endpoint
     *
     * This endpoint allows you to store device token to send notifications to the drivers.
     *
     * @bodyParam   token string required The token generated from OneSignal SDK of the driver.
     *
     * @response {
     *      "status": true,
     *        "message": "Device token has been stored!"
     *  }

     * @response 401 {
     *       "message": "Unauthenticated",
     *  }
     *  }
     */

    function store_token(Request $request){

        $messages = array(
            'token.required' => __('Token field is required.')
        );
        $validator = Validator::make($request->all(), [
            'token' => 'required'
        ], $messages);

        if ($validator->fails()) {
            return response()->json(['status' => false, 'errors' => $validator->errors()], 422);
        }

        $user = $request->user();

        $token = array();
        $token['user_id'] = $user->id;
        $token['token'] = $request->token;
        UserToken::create($token);

        return response()->json(['status' => true, 'message' => "Device token has been stored!"]);

    }



    /**
     * Logout Endpoint
     *
     * This endpoint allows you to remove driver token generated for authentication to logout user.
     * To logout token must be required in header otherwise driver will be Unauthenticated.
     *
     * @header Authorization Bearer $token
     *
     * @response {
     *      "status": true,
     *        "message": "You have successfully logged out!"
     *  }

     * @response 401 {
     *        "message": "Unauthenticated."
     *  }
     */

    function logout(Request $request)
    {
        $request->user()->tokens()->delete();

        return [
            'status' => true,
            'message' => 'You have successfully logged out!'
        ];
    }

    /**
     * Driver Status Endpoint
     *
     * This endpoint allows you to online/offline it's availability.
     * To do this need authorization token.
     *
     * @header Authorization Bearer $token
     * @bodyParam status boolean required The status need be 1 when online and 0 when offline.
     * 
     *
     * @response {
     *       "status": true,
     *       "message": "Status has been changed!",
     *       "current_status": 1
     *   }
     * 
     * @response 401 {
     *        "message": "Unauthenticated."
     *  }
     */

    function online_offline_status(Request $request){

        $messages = array(
            'status.required' => __('Status field is required.')
        );
        $validator = Validator::make($request->all(), [
            'status' => 'required',
        ], $messages);

        if ($validator->fails()) {
            return response()->json(['status' => false, 'errors' => $validator->errors()]);
        }

        $driver_id = $request->user()->id;
        $driver = User::find($driver_id);
        if($driver){
            $driver->online_status = $request->status;
            $driver->save();
            return response()->json(['status' => true, 'message' => "Status has been changed!", 'current_status' => $driver->online_status]);
        }
        return response()->json(['status' => false, 'message' => "No user found!"]);
    }

     /**
     * Driver Location Update Endpoint
     *
     * This endpoint allows you to update driver recent location coordinates.
     * To do this need authorization token.
     *
     * @header Authorization Bearer $token
     * @bodyParam lat float required The latitude of the current location of driver.
     * @bodyParam lng float required The longitude of the current location of driver.
     * 
     * @response {
     *       "status": true,
     *       "message": "Driver location has been updated!!"
     *   }
     * 
     * @response 401 {
     *        "message": "Unauthenticated."
     *  }
     */
    function save_driver_locations(Request $request){

        $messages = array(
            'lat.required' => __('Lat field is required.'),
            'lng.required' => __('Lng field is required.'),
        );
        $validator = Validator::make($request->all(), [
            'lat' => 'required',
            'lng' => 'required',
        ], $messages);

        if ($validator->fails()) {
            return response()->json(['status' => false, 'errors' => $validator->errors()]);
        }
        $driver_id = $request->user()->id;
        $location = array();
        $location['driver_id'] = $driver_id;
        $location['lat'] = $request->lat;
        $location['lng'] = $request->lng;

        DriverLocation::create($location);
        return response()->json(['status' => true, 'message' => "Driver location has been updated!"]);
    }
}
